// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-6vSobjS5xi9_90kecagLS1OQSGDBUM',
    appId: '1:72582076219:web:457f9ecbb3261daeacc91e',
    messagingSenderId: '72582076219',
    projectId: 'ankaso',
    authDomain: 'ankaso.firebaseapp.com',
    storageBucket: 'ankaso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRc2E_Sqwj7lDfau9n5YixbrDq4Ibls50',
    appId: '1:72582076219:android:40ddd26c4fca02cbacc91e',
    messagingSenderId: '72582076219',
    projectId: 'ankaso',
    storageBucket: 'ankaso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA61lzBzV1BjhKuoO8WO3AJS59Np95RDAQ',
    appId: '1:72582076219:ios:bafc6a7706ee833bacc91e',
    messagingSenderId: '72582076219',
    projectId: 'ankaso',
    storageBucket: 'ankaso.firebasestorage.app',
    iosBundleId: 'com.ankaso.ankaso',
  );
}
